name: flutter_application_1
description: A new Flutter project
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  google_fonts: ^6.2.1
  flutter_localizations:
    sdk: flutter
  flutter_gen: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  generate: true   # <-- this is what enables flutter_gen for localization
